import = [
    "~/.config/alacritty/themes/themes/breeze.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 13


[keyboard]
bindings = [
	 { key= "Left",   mods= "Alt",     chars= "\u001BB"			} # Skip word left
	,{ key= "Right",  mods= "Alt",     chars= "\u001BF"			} # Skip word right
	,{ key= "Left",   mods= "Command", chars= "\u001bOH", mode= "AppCursor" } # Home
	,{ key= "Right",  mods= "Command", chars= "\u001bOF", mode= "AppCursor" } # End
	,{ key= "Back",   mods= "Command", chars= "\u0015" 			} # Delete line
	,{ key= "Back",   mods= "Alt",     chars= "\u001b\u007f" 		} # Delete word
	,{ key= "c",      mods= "Command", action= "Copy" 			} # Copy to Clipboard
]
